import React,{useState} from 'react';
import {Card,Field,PrimaryButton} from '../primitives';
import {inputStyle} from '../../theme';
import {NumberField,grid} from './shared';
export default function HealthProfile({t,profile,onSave,busy}){
 const [p,setP]=useState({...profile,targets:{...profile.targets},allergies:profile.allergies||[]});
 const change=(k,v)=>setP(x=>({...x,[k]:v}));
 return <Card t={t}><h2>Your health preferences</h2><p>Saved privately to your account. These guide food choices; they are not a medical assessment.</p><form onSubmit={e=>{e.preventDefault();onSave({...p,age:Number(p.age),weeklyMinutes:Number(p.weeklyMinutes||150),targets:Object.fromEntries(Object.entries(p.targets).filter(([,v])=>v!==''&&v!=null).map(([k,v])=>[k,Number(v)]))});}}><fieldset disabled={busy} style={{border:0,padding:0}}><div style={grid}>
 <NumberField t={t} label="Age" value={p.age} onChange={v=>change('age',v)} min={1} max={100} step={1} required/>
 <Field t={t} label="Goal"><select style={inputStyle(t)} value={p.goal||'wellbeing'} onChange={e=>change('goal',e.target.value)}><option value="wellbeing">Everyday wellbeing</option><option value="strength">Build strength</option><option value="endurance">Build endurance</option><option value="consistency">Build consistency</option></select></Field>
 <Field t={t} label="Food preference"><select style={inputStyle(t)} value={p.diet||'vegetarian'} onChange={e=>change('diet',e.target.value)}><option value="vegetarian">Vegetarian</option><option value="vegan">Vegan</option><option value="eggs">Vegetarian + eggs</option></select></Field>
 <Field t={t} label="Health considerations"><select style={inputStyle(t)} required value={p.medicalStatus||''} onChange={e=>change('medicalStatus',e.target.value)}><option value="">Please choose</option><option value="none">None of the following</option><option value="condition">Medical condition / prescribed diet</option><option value="pregnancy">Pregnant or breastfeeding</option><option value="eating-disorder">Current or past eating disorder</option><option value="unsure">Unsure / prefer not to say</option></select></Field>
 <NumberField t={t} label="My weekly activity goal (minutes)" value={p.weeklyMinutes??150} onChange={v=>change('weeklyMinutes',v)} min={10} max={2000} step={1}/>
 </div><fieldset style={{border:`1px solid ${t.line}`,borderRadius:12,marginBottom:16}}><legend>Allergies / exclusions</legend>{[['eggs','Eggs'],['gluten','Gluten / oats'],['legumes','Legumes (lentils, chickpeas)']].map(([k,label])=><label key={k} style={{display:'inline-flex',gap:8,margin:10}}><input type="checkbox" checked={p.allergies.includes(k)} onChange={e=>change('allergies',e.target.checked?[...p.allergies,k]:p.allergies.filter(a=>a!==k))}/>{label}</label>)}<Field t={t} label="Other allergies (leave blank if none)"><input style={inputStyle(t)} maxLength={200} value={p.otherAllergies||''} onChange={e=>change('otherAllergies',e.target.value)}/></Field></fieldset>
 <label style={{display:'flex',gap:10,marginBottom:18}}><input type="checkbox" checked={!!p.injury} onChange={e=>change('injury',e.target.checked)}/>Injury, pain, or a restriction affecting exercise</label>
 <details><summary>Optional daily targets from your own plan or dietitian</summary><p>Leave blank if unknown. These are comparison targets, not a diagnosis of what your body lacks.</p><div style={grid}>{[['cal','Energy (kcal)',10000],['protein','Protein (g)',500],['fiber','Fibre (g)',100],['calcium','Calcium (mg)',2500],['iron','Iron (mg)',45],['potassium','Potassium (mg)',10000]].map(([k,label,max])=><NumberField key={k} t={t} label={label} value={p.targets[k]} max={max} onChange={v=>setP(x=>({...x,targets:{...x.targets,[k]:v}}))}/>)}</div></details>
 <PrimaryButton t={t} type="submit" style={{marginTop:16}} disabled={busy}>{busy?'Saving…':'Save health preferences'}</PrimaryButton></fieldset></form></Card>;
}
