import React,{useState} from 'react';
import {Card,Field,PrimaryButton,GhostButton} from './primitives';
import {inputStyle} from '../theme';
export default function AIConnections({t,user}){
 const [state,setState]=useState(null),[key,setKey]=useState(''),[model,setModel]=useState('openai/gpt-oss-20b'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function request(method='GET',body){
  const token=await user.getIdToken();
  const r=await fetch('/api/auth/welcome?action=ai-connections',{method,cache:'no-store',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','X-Lifeos-Admin':'1'},...(body?{body:JSON.stringify(body)}:{})});
  const result=await r.json();if(!r.ok)throw Error(result.error||'Could not update this connection.');return result;
 }
 async function run(fn){setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(e.message||'Please retry.');}finally{setBusy(false);}}
 const load=()=>run(async()=>{const value=await request();setState(value);setModel(value.model||'openai/gpt-oss-20b');});
 return <Card t={t} style={{marginTop:20}}><h2>AI Connections</h2><p>Gemini remains available. The Groq operator uses a separate owner-managed connection.</p><details><summary>Account ID for owner verification</summary><p>This ID is not a password or API key.</p><input aria-label="Your Life OS account ID" readOnly value={user.uid} style={inputStyle(t)}/><GhostButton t={t} onClick={()=>run(async()=>{await navigator.clipboard.writeText(user.uid);setMessage('Account ID copied.');})}>Copy account ID</GhostButton></details><GhostButton t={t} disabled={busy} onClick={load}>Open connection settings</GhostButton>
 {state?.ownerConfigured===false&&<p>Owner access is awaiting verification. Send your account ID to the developer to bind this page to your account. The API key field stays locked until then.</p>}
 {state?.ownerConfigured&&<form onSubmit={e=>{e.preventDefault();run(async()=>{try{const result=await request('PUT',{key,model,revision:state.revision});setState({...result,ownerConfigured:true});setMessage('Groq key accepted and saved securely. Open Operator to try it.');}finally{setKey('');}});}}><p>{state.configured?'Groq connected · key is never displayed':'Groq not connected'}</p><Field t={t} label="Groq API key"><input type="password" autoComplete="new-password" spellCheck={false} autoCapitalize="none" value={key} maxLength={256} required onChange={e=>setKey(e.target.value)} style={inputStyle(t)}/></Field><Field t={t} label="Operator model"><select style={inputStyle(t)} value={model} onChange={e=>setModel(e.target.value)}><option value="openai/gpt-oss-20b">GPT OSS 20B</option><option value="openai/gpt-oss-120b">GPT OSS 120B</option></select></Field><p>Sign in within the last five minutes to save or disconnect. The server encrypts this key; it is not stored in your browser or GitHub.</p><PrimaryButton t={t} type="submit" disabled={busy||!key}>{busy?'Checking…':'Save & test Groq'}</PrimaryButton>{state.configured&&<GhostButton t={t} disabled={busy} onClick={()=>{if(window.confirm('Disconnect Groq for all Life OS users?'))run(async()=>{const result=await request('DELETE',{model,revision:state.revision});setState({...result,ownerConfigured:true});setKey('');setMessage('Groq disconnected. Gemini is unchanged.');});}}>Disconnect Groq</GhostButton>}</form>}
 {message&&<p role="status">{message}</p>}</Card>;
}
